# -*- coding: utf-8 -*-
"""ejercicioTwoSeleccion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1m-5dhBd3pXEOmhOi-vLngh7H8xiieI

# Ejercicio 02 - Semana 02
Ordenación por selección - 10 arreglos, una sola ejecución
"""

arrays = [
    [7, 84, 302, 1450, 9, 26, 718, 4005, 113, 3],
    [950, 4, 62, 3201, 17, 508, 2, 89, 1746, 231],
    [35, 807, 6, 2419, 71, 105, 9, 4382, 20, 563],
    [1204, 8, 97, 453, 2, 3087, 61, 749, 15, 5026],
    [73, 1905, 4, 286, 9012, 38, 617, 1, 54, 3240],
    [603, 29, 4751, 5, 184, 92, 7, 2306, 841, 16],
    [3, 7502, 48, 916, 120, 6, 3491, 75, 208, 5643],
    [468, 2, 3970, 81, 705, 14, 6238, 9, 36, 1542],
    [56, 8041, 7, 390, 24, 1675, 908, 1, 63, 4210],
    [2017, 45, 8, 732, 91, 5004, 3, 268, 6471, 19],
]

def selectionSort(arr):
    workingList = arr[:]
    n = len(workingList)
    swapCount = 0
    for i in range(n - 1):
        minIndex = i
        for j in range(i + 1, n):
            if workingList[j] < workingList[minIndex]:
                minIndex = j
        if minIndex != i:
            workingList[i], workingList[minIndex] = workingList[minIndex], workingList[i]
            swapCount += 1
    return workingList, swapCount

for idx, arr in enumerate(arrays, start=1):
    sortedList, swapCount = selectionSort(arr)
    print(f"Arreglo {idx}")
    print("  Entrada:", arr)
    print("  Salida: ", sortedList)
    print("  Intercambios:", swapCount)
    print()