# -*- coding: utf-8 -*-
"""Ejercicio01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kkclzwREtBSeiCEQeGhsN8lMzX-MCbo
"""

import time

def busquedaLineal(lista, objetivo):
    """Recorre la lista de inicio a fin comparando elemento por elemento."""
    comparaciones = 0
    for indice, valor in enumerate(lista):
        comparaciones += 1
        if valor == objetivo:
            return indice, comparaciones
    return -1, comparaciones


def busquedaBinaria(lista, objetivo):
    """Divide el espacio de busqueda a la mitad en cada paso (lista ordenada)."""
    izquierda, derecha = 0, len(lista) - 1
    comparaciones = 0

    while izquierda <= derecha:
        medio = (izquierda + derecha) // 2
        comparaciones += 1
        valorMedio = lista[medio]

        if valorMedio == objetivo:
            return medio, comparaciones
        elif valorMedio < objetivo:
            izquierda = medio + 1
        else:
            derecha = medio - 1

    return -1, comparaciones


def medirBusqueda(funcionBusqueda, lista, objetivo):
    """Ejecuta una funcion de busqueda y cronometra su duracion."""
    inicio = time.perf_counter()
    posicion, comparaciones = funcionBusqueda(lista, objetivo)
    tiempoMs = (time.perf_counter() - inicio) * 1000
    return posicion, comparaciones, tiempoMs


def mostrarResultado(nombre, posicion, comparaciones, tiempoMs):
    print(f"{nombre}")
    print(f"  Posicion:      {posicion}")
    print(f"  Comparaciones: {comparaciones}")
    print(f"  Tiempo:        {tiempoMs:.4f} ms")


def main():
    datos = list(range(1, 100_001))
    objetivo = 99_999

    posLineal, compLineal, tiempoLineal = medirBusqueda(busquedaLineal, datos, objetivo)
    posBinaria, compBinaria, tiempoBinaria = medirBusqueda(busquedaBinaria, datos, objetivo)

    assert posLineal == posBinaria, "Ambos metodos deben encontrar la misma posicion"

    mostrarResultado("BUSQUEDA LINEAL", posLineal, compLineal, tiempoLineal)
    print()
    mostrarResultado("BUSQUEDA BINARIA", posBinaria, compBinaria, tiempoBinaria)

    print("\nCOMPARACION")
    ahorro = compLineal - compBinaria
    factor = compLineal / compBinaria if compBinaria else float("inf")
    print(f"  La busqueda binaria hizo {ahorro} comparaciones menos ({factor:.1f}x mas eficiente)")


if __name__ == "__main__":
    main()

import time

def busquedaLineal(lista, objetivo):
    """Recorre la lista de inicio a fin comparando elemento por elemento."""
    comparaciones = 0
    for indice, valor in enumerate(lista):
        comparaciones += 1
        if valor == objetivo:
            return indice, comparaciones
    return -1, comparaciones


def busquedaBinaria(lista, objetivo):
    """Divide el espacio de busqueda a la mitad en cada paso (lista ordenada)."""
    izquierda, derecha = 0, len(lista) - 1
    comparaciones = 0

    while izquierda <= derecha:
        medio = (izquierda + derecha) // 2
        comparaciones += 1
        valorMedio = lista[medio]

        if valorMedio == objetivo:
            return medio, comparaciones
        elif valorMedio < objetivo:
            izquierda = medio + 1
        else:
            derecha = medio - 1

    return -1, comparaciones


def medirBusqueda(funcionBusqueda, lista, objetivo):
    """Ejecuta una funcion de busqueda y cronometra su duracion."""
    inicio = time.perf_counter()
    posicion, comparaciones = funcionBusqueda(lista, objetivo)
    tiempoMs = (time.perf_counter() - inicio) * 1000
    return posicion, comparaciones, tiempoMs


def mostrarResultado(nombre, posicion, comparaciones, tiempoMs):
    print(f"{nombre}")
    print(f"  Posicion:      {posicion}")
    print(f"  Comparaciones: {comparaciones}")
    print(f"  Tiempo:        {tiempoMs:.4f} ms")


def main():
    datos = list(range(1, 200_001))
    objetivo = 175_432

    posLineal, compLineal, tiempoLineal = medirBusqueda(busquedaLineal, datos, objetivo)
    posBinaria, compBinaria, tiempoBinaria = medirBusqueda(busquedaBinaria, datos, objetivo)

    assert posLineal == posBinaria, "Ambos metodos deben encontrar la misma posicion"

    mostrarResultado("BUSQUEDA LINEAL", posLineal, compLineal, tiempoLineal)
    print()
    mostrarResultado("BUSQUEDA BINARIA", posBinaria, compBinaria, tiempoBinaria)

    print("\nCOMPARACION")
    ahorro = compLineal - compBinaria
    factor = compLineal / compBinaria if compBinaria else float("inf")
    print(f"  La busqueda binaria hizo {ahorro} comparaciones menos ({factor:.1f}x mas eficiente)")


if __name__ == "__main__":
    main()