# -*- coding: utf-8 -*-
"""practicaOrdenacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qHRVh1GsIexep2eFsbmbJn0rbsmAooD

# Práctica de Laboratorio - Algoritmos de Ordenación en Python
Curso: Análisis y Diseño de Algoritmos
Nombre: Jacob Baños Pacco

## Ejercicio 1 - Ordenación por intercambio
Lista de trabajo: [12, 5, 9, 3, 15, 1]
"""

workingList = [12, 5, 9, 3, 15, 1]
print("Lista original:", workingList)

n = len(workingList)
totalSwaps = 0

for passNum in range(n - 1):
    swapped = False
    for j in range(n - 1 - passNum):
        if workingList[j] > workingList[j + 1]:
            workingList[j], workingList[j + 1] = workingList[j + 1], workingList[j]
            totalSwaps += 1
            swapped = True
    print(f"Pasada {passNum + 1}:", workingList)
    if not swapped:
        break

print("Lista final ordenada:", workingList)
print("Total de intercambios:", totalSwaps)

"""## Ejercicio 2 - Ordenación por selección
Lista de trabajo: [20, 8, 14, 2, 11, 6]
"""

workingList = [20, 8, 14, 2, 11, 6]
print("Lista original:", workingList)

n = len(workingList)

for i in range(n - 1):
    minIndex = i
    for j in range(i + 1, n):
        if workingList[j] < workingList[minIndex]:
            minIndex = j
    minValue = workingList[minIndex]
    workingList[i], workingList[minIndex] = workingList[minIndex], workingList[i]
    print(f"Pasada {i + 1}: seleccionado {minValue} (posición original {minIndex}) ->", workingList)

print("Lista final ordenada:", workingList)

"""## Ejercicio 3 - Ordenación por inserción
Lista de trabajo: [18, 7, 10, 4, 13, 2]
"""

workingList = [18, 7, 10, 4, 13, 2]
print("Lista original:", workingList)

n = len(workingList)

for i in range(1, n):
    key = workingList[i]
    j = i - 1
    while j >= 0 and workingList[j] > key:
        workingList[j + 1] = workingList[j]
        j -= 1
    workingList[j + 1] = key
    print(f"Paso {i}: insertado {key} ->", workingList)

print("Lista final ordenada:", workingList)

"""## Ejercicio 4 - Orden descendente
Lista de trabajo: [9, 17, 4, 12, 6, 1]
Algoritmo elegido: selección, invirtiendo la condición para buscar el máximo en vez del mínimo.
"""

workingList = [9, 17, 4, 12, 6, 1]
print("Lista original:", workingList)

n = len(workingList)

for i in range(n - 1):
    maxIndex = i
    for j in range(i + 1, n):
        if workingList[j] > workingList[maxIndex]:
            maxIndex = j
    workingList[i], workingList[maxIndex] = workingList[maxIndex], workingList[i]
    print(f"Pasada {i + 1}:", workingList)

print("Lista final (descendente):", workingList)

"""## Ejercicio 5 - Detección y corrección de error
Código original (ordena descendente por error): condición `lista[i] < lista[j]`.
Corrección: cambiar la condición a `lista[i] > lista[j]` para que ordene de menor a mayor.
"""

lista = [10, 3, 7, 1, 5]

for i in range(len(lista)):
    for j in range(i + 1, len(lista)):
        if lista[i] > lista[j]:
            aux = lista[i]
            lista[i] = lista[j]
            lista[j] = aux

print("Lista ordenada:", lista)